X=MsgBox("ERROR while opening File. Do you want fix it ?",3+64,"COMPUTER")
X=MsgBox("unable to fix the error. DO you want close The file ",3+48,"COMPUTER SCAN")

X=MsgBox("Alert ! Virus has been detected. Do tou want to delete the virus",3+16,"VIRUS !")

X=MsgBox("Unable to delete Virus",1+64,"SYSTEM !")

X=MsgBox("VIRUS IS ACTIVATED SUCCESSFUL !",2+16,"VIRUS ALERT")

X=MsgBox("Deleting system File....",2+16,"File Deletion ")
X=MsgBox(" Virus trying to copy your Password and other Data.....!",2+48,"VIRUS ALERT")
X=MsgBox("Please wait ! your critical fiels uploading to your server. Do you want to stop it ?",4+64,"FILE TRANSFERING")

X=MsgBox("Can't Stopped Transfer",3+64,"PROCESS")
X=MsgBox("Transfer is completed.",2+16,"COMPLETED")

X=MsgBox("Your computer is Hacked .All file uploaded to server",2+16,"HACKED")

X=MsgBox("You can't Access  your computer anymore......",1+48,"ERROR!")


X=MsgBox("Virus still Activated. Windows system takes action shortly",3+16,"VIRUS !")
X=MsgBox("Virus Down Temprory ! Do you want continue",3+64,"COMPUTER")

X=MsgBox("please shut down your computer instantly ",3+48,"SHUTDOWN")




X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")

X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")

X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")

X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")

X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
X=MsgBox("HACKED...!",3+64,"VIRUS")
